name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  preflight:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.11
          extra_nix_config: |
            extra-platforms = aarch64-linux

      - name: Dependencies
        run: nix develop --command pnpm install

      - name: Build
        run: nix develop --command tree-sitter build

      - name: Unit Tests
        run: nix develop --command tree-sitter -r test
